/*
  filename: integralui.base.grid.js
  version : 1.3.0
  Copyright © 2016-2017 Lidor Systems. All rights reserved.

  This file is part of the "IntegralUI Web" Library. 
                                                                   
  The contents of this file are subject to the IntegralUI Web License, and may not be used except in compliance with the License.
  A copy of the License should have been installed in the product's root installation directory or it can be found at
  http://www.lidorsystems.com/products/web/studio/license-agreement.aspx.
                                                            
  This SOFTWARE is provided "AS IS", WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the specific language 
  governing rights and limitations under the License. Any infringement will be prosecuted under applicable laws.                           
*/
var __extends=this&&this.__extends||function(k,b){function a(){this.constructor=k}for(var c in b)b.hasOwnProperty(c)&&(k[c]=b[c]);k.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)},__decorate=this&&this.__decorate||function(k,b,a,c){var e=arguments.length,d=3>e?b:null===c?c=Object.getOwnPropertyDescriptor(b,a):c,h;if("object"===typeof Reflect&&"function"===typeof Reflect.decorate)d=Reflect.decorate(k,b,a,c);else for(var f=k.length-1;0<=f;f--)if(h=k[f])d=(3>e?h(d):3<e?h(b,a,d):
h(b,a))||d;return 3<e&&d&&Object.defineProperty(b,a,d),d},__metadata=this&&this.__metadata||function(k,b){if("object"===typeof Reflect&&"function"===typeof Reflect.metadata)return Reflect.metadata(k,b)},core_1=require("@angular/core"),integralui_core_1=require("./integralui.core"),integralui_common_service_1=require("../services/integralui.common.service"),integralui_data_service_1=require("../services/integralui.data.service"),integralui_dragdrop_service_1=require("../services/integralui.dragdrop.service"),
integralui_filter_service_1=require("../services/integralui.filter.service"),IntegralUIDirection;(function(k){k[k.After=0]="After";k[k.At=1]="At";k[k.Before=2]="Before";k[k.Down=3]="Down";k[k.First=4]="First";k[k.Left=5]="Left";k[k.Last=6]="Last";k[k.Right=7]="Right";k[k.Up=8]="Up"})(IntegralUIDirection=exports.IntegralUIDirection||(exports.IntegralUIDirection={}));var IntegralUIGridLines;
(function(k){k[k.None=0]="None";k[k.Horizontal=1]="Horizontal";k[k.Vertical=2]="Vertical";k[k.Both=3]="Both"})(IntegralUIGridLines=exports.IntegralUIGridLines||(exports.IntegralUIGridLines={}));
var IntegralUIBaseGrid=function(k){function b(a,c,e,b,h,f,g){var d=k.call(this,h)||this;d.dataService=a;d.dragDropService=c;d.elemRef=e;d.elemRenderer=b;d.commonService=h;d.filterService=f;d.cmpResolver=g;d.currentColumnList=[];d.currentRowList=[];d.dataColumns=[];d.dataRows=[];d.options={};d.scrollColumnList=[];d.scrollRowList=[];d.columnDataKey="columns";d.rowDataKey="rows";d.dropMarkElem=null;d.dragCmpRef=null;d.dragCmp=null;d.cloneElem=null;d.cloneElemStartPos={x:0,y:0};d.expandColIndex=0;d.hoverColumn=
null;d.hoverRow=null;d.currentIndex=0;d.prevIndex=0;d.columnStartPos={x:0,y:0};d.resizeColumn=null;d.resizeColumnIndex=-1;d.reorderColumn=null;d.columnReorderActive=!1;d.currentFocusCell=null;d.isKeyboardActive=!1;d.allowUpdate=!0;d.avgRowHeight=0;d.columnPadding={top:0,right:0,bottom:0,left:0};d.currentGridLines=IntegralUIGridLines.Both;d.headerHeight=0;d.footerHeight=0;d.viewIndexRange={left:0,middle:999,right:999};d.visibleRange=1;d.isAutoSizeColumnsActive=!1;d.isHeaderVisible=!0;d.isFooterVisible=
!0;d.scrollSize={width:0,height:0};d.clientRect={width:0,height:0};d.contentLeftPos=0;d.allColWidth=0;d.prevClientRect={width:0,height:0};d.isColumnResizing=!1;d.currentScrollPos={x:0,y:0};d.maxScrollPos={x:0,y:0};d.accelerator=.5;d.scrollTimerID=null;d.isScrollTimerActive=!1;d.scrollCount=0;d.isScrollActive=!1;d.prevScrollPos={x:0,y:0};d.scrollBarSize={width:0,height:0};d.scrollLargeChange={x:0,y:0};d.currentSelectedColumn=null;d.currentSelectedRow=null;d.currentSelectionMode=integralui_core_1.IntegralUISelectionMode.One;
d.shiftFirstSelectedRow=null;d.removeIndex=-1;d.currentSelectedRows=[];d.rowHeight=0;d.afterSelect=new core_1.EventEmitter;d.beforeEdit=new core_1.EventEmitter;d.beforeSelect=new core_1.EventEmitter;d.beforeUpdate=new core_1.EventEmitter;d.change=new core_1.EventEmitter;d.columnAdding=new core_1.EventEmitter;d.columnAdded=new core_1.EventEmitter;d.columnClick=new core_1.EventEmitter;d.columnRemoving=new core_1.EventEmitter;d.columnRemoved=new core_1.EventEmitter;d.columnsCleared=new core_1.EventEmitter;
d.columnSizeChanged=new core_1.EventEmitter;d.dragDrop=new core_1.EventEmitter;d.dragOver=new core_1.EventEmitter;d.keyDown=new core_1.EventEmitter;d.keyPress=new core_1.EventEmitter;d.keyUp=new core_1.EventEmitter;d.rowAdding=new core_1.EventEmitter;d.rowAdded=new core_1.EventEmitter;d.rowClick=new core_1.EventEmitter;d.rowDblClick=new core_1.EventEmitter;d.rowRemoving=new core_1.EventEmitter;d.rowRemoved=new core_1.EventEmitter;d.rowsCleared=new core_1.EventEmitter;d.loadComplete=new core_1.EventEmitter;
d.scrollPosChanged=new core_1.EventEmitter;d.selectionChanged=new core_1.EventEmitter;d.updateComplete=new core_1.EventEmitter;d.sortColumn=null;d.sortComparer=null;d.updateOptions();return d}__extends(b,k);Object.defineProperty(b.prototype,"allowDrag",{set:function(a){this.options.allowDrag=a},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"allowDrop",{set:function(a){this.options.allowDrop=a},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"allowFilter",{set:function(a){this.options.allowFilter=
a},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"allowFocus",{set:function(a){this.options.allowFocus=a;a||(this.currentFocusCell=null);this.refresh()},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"autoSizeColumns",{get:function(){return this.isAutoSizeColumnsActive},set:function(a){this.isAutoSizeColumnsActive!=a&&(this.isAutoSizeColumnsActive=a,this.updateLayout())},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"columns",{get:function(){return this.dataColumns},
set:function(a){this.dataColumns=a;this.updateData()},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"dataFields",{set:function(a){this.updateDataFields(a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"focusedCell",{get:function(){return this.currentFocusCell},set:function(a){this.currentFocusCell!=a&&(this.currentFocusCell=a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"gridLines",{get:function(){return this.currentGridLines},set:function(a){this.currentGridLines!=
a&&(this.currentGridLines=a,this.refresh())},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"paging",{set:function(a){this.updatePaging(a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"rows",{get:function(){return this.dataRows},set:function(a){this.dataRows=a;this.updateData()},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"selectedColumn",{get:function(){return this.currentSelectedColumn},set:function(a){this.currentSelectedColumn!=a&&
this.processColumnSelection(null,a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"selectedRow",{get:function(){return this.currentSelectedRow},set:function(a){this.currentSelectedRow!=a&&this.processRowSelection(null,a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"selectionMode",{get:function(){return this.currentSelectionMode},set:function(a){this.currentSelectionMode!=a&&(this.currentSelectionMode=a,this.clearPrevSelection(this.currentSelectionMode!=
integralui_core_1.IntegralUISelectionMode.None?this.currentSelectedRow:null),this.refresh(),this.currentSelectionMode==integralui_core_1.IntegralUISelectionMode.None&&(this.currentSelectedRow=null,this.selectionChanged.emit(null)))},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"showScroll",{get:function(){return this.options.showScroll},set:function(a){this.updateShowScroll(a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"sorting",{set:function(a){this.options.sorting=
a},enumerable:!0,configurable:!0});b.prototype.ngOnInit=function(){this.dataService.init([{data:this.columns,fields:this.options.columnFields,key:this.columnDataKey},{data:this.rows,fields:this.options.rowFields,key:this.rowDataKey}])};b.prototype.addColumn=function(a){this.callEventAddColumn("add",a)};b.prototype.clearColumns=function(){this.dataService.clear(null,this.columnDataKey);this.columnsCleared.emit(null);this.currentScrollPos.x=0};b.prototype.insertColumnAt=function(a,c){this.callEventAddColumn("at",
a,c)};b.prototype.insertColumnBefore=function(a,c){this.callEventAddColumn("ref",a,-1,c)};b.prototype.insertColumnAfter=function(a,c){this.callEventAddColumn("ref",a,-1,c,!0)};b.prototype.removeColumn=function(a){return this.callEventRemoveColumn(a)};b.prototype.removeColumnAt=function(a){return this.callEventRemoveColumn(null,a)};b.prototype.callEventAddColumn=function(a,c,e,d,b){var h={cancel:!1,column:c};this.columnAdding.emit(h);if(1!=h.cancel){switch(a){case "at":this.dataService.insert(c,e,
null,null,!1,this.columnDataKey);break;case "ref":this.dataService.insertByRef(c,d,b,this.columnDataKey);break;default:this.dataService.insert(c,-1,null,null,!1,this.columnDataKey)}this.columnAdded.emit({column:c})}};b.prototype.callEventRemoveColumn=function(a,c){var e={cancel:!1,column:a};this.columnRemoving.emit(e);return 1!=e.cancel&&(this.removeIndex=this.columns?this.columns.indexOf(a):-1,e=this.dataService.removeAt(a,c,null,this.columnDataKey),e.result)?(this.columnRemoved.emit({column:e.obj}),
!0):!1};b.prototype.addRow=function(a,c){this.callEventAddRow("add",a,-1,c)};b.prototype.clearRows=function(a){this.dataService.clear(a,this.rowDataKey);this.rowsCleared.emit({parent:a});this.clearSelection();this.currentScrollPos.y=0};b.prototype.insertRowAt=function(a,c,e){this.callEventAddRow("at",a,c,e)};b.prototype.insertRowBefore=function(a,c){this.callEventAddRow("ref",a,-1,null,c)};b.prototype.insertRowAfter=function(a,c){this.callEventAddRow("ref",a,-1,null,c,!0)};b.prototype.removeRow=function(a){return this.callEventRemoveRow(a)};
b.prototype.removeRowAt=function(a,c){return this.callEventRemoveRow(null,a,c)};b.prototype.callEventAddRow=function(a,c,e,d,b,f){var h={cancel:!1,row:c};this.rowAdding.emit(h);if(1!=h.cancel){switch(a){case "at":this.dataService.insert(c,e,d,null,!1,this.rowDataKey);break;case "ref":this.dataService.insertByRef(c,b,f,this.rowDataKey);break;default:this.dataService.insert(c,-1,d,null,!1,this.rowDataKey)}this.rowAdded.emit({row:c})}};b.prototype.callEventRemoveRow=function(a,c,e){var d={cancel:!1,
row:a};this.rowRemoving.emit(d);return 1!=d.cancel&&(this.removeIndex=this.rows?this.rows.indexOf(a):-1,a=this.dataService.removeAt(a,c,e,this.rowDataKey),a.result)?(this.rowRemoved.emit({row:a.obj}),!0):!1};b.prototype.updateData=function(){};b.prototype.updateDataFields=function(a){a?(this.updateColumnFields(a.column),this.updateRowFields(a.row),this.updateCellFields(a.cell)):(this.updateColumnFields(),this.updateRowFields(),this.updateCellFields())};b.prototype.updateOptions=function(a){a?(this.options=
{allowAnimation:this.commonService.isFieldAvailable(a.allowAnimation,!0),allowCellFocus:this.commonService.isFieldAvailable(a.allowCellFocus,!0),allowColumnReorder:this.commonService.isFieldAvailable(a.allowColumnReorder,!1),allowDrag:this.commonService.isFieldAvailable(a.allowDrag,!1),allowDrop:this.commonService.isFieldAvailable(a.allowDrop,!0),allowFilter:this.commonService.isFieldAvailable(a.allowFilter,!1),allowFocus:this.commonService.isFieldAvailable(a.allowFocus,!1),animationSpeed:200,autoExpand:this.commonService.isFieldAvailable(a.autoExpand,
!0),displayMode:this.commonService.isFieldAvailable(a.displayMode,"normal"),editorSettings:{activate:"click"},enabled:this.commonService.isFieldAvailable(a.enabled,!0),expandColIndex:this.commonService.isFieldAvailable(a.expandColIndex,void 0!=this.options.expandColIndex?this.options.expandColIndex:0),fillSpace:this.commonService.isFieldAvailable(a.fillSpace,!1),gridLines:this.commonService.isFieldAvailable(a.gridLines,"both"),hoverSelection:this.commonService.isFieldAvailable(a.hoverSelection,!1),
indent:this.commonService.isFieldAvailable(a.indent,15),labelEdit:this.commonService.isFieldAvailable(a.labelEdit,!1),loadRows:[],mouseWheelSpeed:this.commonService.isFieldAvailable(a.mouseWheelSpeed,"normal"),pathSeparator:this.commonService.isFieldAvailable(a.pathSeparator,"\\"),rowHeight:this.commonService.isFieldAvailable(a.rowHeight,-1),rtl:this.commonService.isFieldAvailable(a.rtl,!1),selectedColumn:this.commonService.isFieldAvailable(a.selectedColumn,this.currentSelectedColumn?this.currentSelectedColumn:
null),selectedIndex:-1,selectedRow:this.commonService.isFieldAvailable(a.selectedRow,this.currentSelectedRow?this.currentSelectedRow:null),selectedRows:[],selectionMode:this.commonService.isFieldAvailable(a.selectionMode,integralui_core_1.IntegralUISelectionMode.One),showFooter:this.commonService.isFieldAvailable(a.showFooter,!0),showHeader:this.commonService.isFieldAvailable(a.showHeader,!0),showIcons:this.commonService.isFieldAvailable(a.showIcons,!0),sorting:this.commonService.isFieldAvailable(a.sorting,
integralui_core_1.IntegralUISortOrder.None)},this.updatePaging(a.paging),this.updateDataFields(a.dataFields),this.updateShowScroll(a.showScroll)):(this.options={allowAnimation:!0,allowCellFocus:!0,allowColumnReorder:!1,allowDrag:!1,allowDrop:!0,allowFilter:!1,allowFocus:!1,animationSpeed:200,autoExpand:!0,displayMode:"normal",editorSettings:{activate:"click"},enabled:!0,expandColIndex:0,fillSpace:!1,gridLines:"both",hoverSelection:!1,indent:15,labelEdit:!1,loadRows:[],mouseWheelSpeed:"normal",pathSeparator:"\\",
rowHeight:-1,rtl:!1,selectedColumn:null,selectedIndex:-1,selectedRow:null,selectedRows:[],selectionMode:integralui_core_1.IntegralUISelectionMode.One,showFooter:!0,showHeader:!0,showIcons:!0,sorting:integralui_core_1.IntegralUISortOrder.None},this.updatePaging(),this.updateDataFields(),this.updateShowScroll())};b.prototype.updateColumnFields=function(a){this.options.columnFields=a?{allowDrag:a.allowDrag?a.allowDrag:"allowDrag",allowDrop:a.allowDrop?a.allowDrop:"allowDrop",allowFilter:a.allowFilter?
a.allowFilter:"allowFilter",allowGrouping:a.allowGrouping?a.allowGrouping:"allowGrouping",allowResize:a.allowResize?a.allowResize:"allowResize",canSelect:a.canSelect?a.canSelect:"canSelect",cellTemplateUrl:a.cellTemplateUrl?a.cellTemplateUrl:"cellTemplateUrl",comparer:a.comparer?a.comparer:"comparer",contentAlignment:a.contentAlignment?a.contentAlignment:"contentAlignment",contextMenu:a.contextMenu?a.contextMenu:"contextMenu",editorType:a.editorType?a.editorType:"editorType",editorSettings:a.editorSettings?
a.editorSettings:"editorSettings",editorTemplate:a.editorTemplate?a.editorTemplate:"editorTemplate",filterParams:a.filterParams?a.filterParams:"filterParams",filterTemplate:a.filterTemplate?a.filterTemplate:"filterTemplate",fixed:a.fixed?a.fixed:"fixed",fixedWidth:a.fixedWidth?a.fixedWidth:"fixedWidth",footerAlignment:a.footerAlignment?a.footerAlignment:"footerAlignment",footerContent:a.footerContent?a.footerContent:"footerContent",footerTemplate:a.footerTemplate?a.footerTemplate:"footerTemplate",
footerTemplateModel:a.footerTemplateModel?a.footerTemplateModel:"footerTemplateModel",footerText:a.footerText?a.footerText:"footerText",footerTooltip:a.footerTooltip?a.footerTooltip:"footerTooltip",groupText:a.groupText?a.groupText:"groupText",headerAlignment:a.headerAlignment?a.headerAlignment:"headerAlignment",headerContent:a.headerContent?a.headerContent:"headerContent",headerTemplate:a.headerTemplate?a.headerTemplate:"headerTemplate",headerTemplateModel:a.headerTemplateModel?a.headerTemplateModel:
"headerTemplateModel",headerText:a.headerText?a.headerText:"headerText",headerTooltip:a.headerTooltip?a.headerTooltip:"headerTooltip",icon:a.icon?a.icon:"icon",id:a.id?a.id:"id",minWidth:a.minWidth?a.minWidth:"minWidth",maxWidth:a.maxWidth?a.maxWidth:"maxWidth",selected:a.selected?a.selected:"selected",style:a.style?a.style:"style",templateSettings:a.templateSettings?a.templateSettings:"templateSettings",visible:a.visible?a.visible:"visible",width:a.width?a.width:"width"}:{allowDrag:"allowDrag",allowDrop:"allowDrop",
allowFilter:"allowFilter",allowGrouping:"allowGrouping",allowResize:"allowResize",canSelect:"canSelect",cellTemplateUrl:"cellTemplateUrl",comparer:"comparer",contentAlignment:"contentAlignment",contextMenu:"contextMenu",editorType:"editorType",editorSettings:"editorSettings",editorTemplate:"editorTemplate",filterParams:"filterParams",filterTemplate:"filterTemplate",footerTemplateModel:"footerTemplateModel",fixed:"fixed",fixedWidth:"fixedWidth",footerAlignment:"footerAlignment",footerContent:"footerContent",
footerTemplate:"footerTemplate",footerText:"footerText",footerTooltip:"footerTooltip",groupText:"groupText",headerAlignment:"headerAlignment",headerContent:"headerContent",headerTemplate:"headerTemplate",headerTemplateModel:"headerTemplateModel",headerText:"headerText",headerTooltip:"headerTooltip",icon:"icon",id:"id",minWidth:"minWidth",maxWidth:"maxWidth",selected:"selected",style:"style",templateSettings:"templateSettings",visible:"visible",width:"width"};this.dataService&&this.dataService.updateDataFields(this.options.columnFields,
this.columnDataKey)};b.prototype.updateRowFields=function(a){this.options.rowFields=a?{allowDrag:a.allowDrag?a.allowDrag:"allowDrag",allowDrop:a.allowDrop?a.allowDrop:"allowDrop",allowEdit:a.allowEdit?a.allowEdit:"allowEdit",allowFocus:a.allowFocus?a.allowFocus:"allowFocus",autoCheck:a.autoCheck?a.autoCheck:"autoCheck",canSelect:a.canSelect?a.canSelect:"canSelect",cells:a.cells?a.cells:"cells",checkBoxSettings:a.checkBoxSettings?a.checkBoxSettings:"checkBoxSettings",checked:a.checked?a.checked:"checked",
checkState:a.checkState?a.checkState:"checkState",content:a.content?a.content:"content",contextMenu:a.contextMenu?a.contextMenu:"contextMenu",gid:a.gid?a.gid:"gid",enabled:a.enabled?a.enabled:"enabled",expanded:a.expanded?a.expanded:"expanded",fixed:a.fixed?a.fixed:"fixed",hasChildren:a.hasChildren?a.hasChildren:"hasChildren",icon:a.icon?a.icon:"icon",id:a.id?a.id:"id",objects:a.rows?a.rows:"rows",pid:a.pid?a.pid:"pid",rows:a.rows?a.rows:"rows",selected:a.selected?a.selected:"selected",statusIcon:a.statusIcon?
a.statusIcon:"statusIcon",style:a.style?a.style:"style",subobjects:a.cells?a.cells:"cells",templateObj:a.templateObj?a.templateObj:"templateObj",text:a.text?a.text:"text",tooltip:a.tooltip?a.tooltip:"tooltip",value:a.value?a.value:"value",visible:a.visible?a.visible:"visible"}:{allowDrag:"allowDrag",allowDrop:"allowDrop",allowFocus:"allowFocus",canSelect:"canSelect",cells:"cells",content:"content",contextMenu:"contextMenu",enabled:"enabled",expanded:"expanded",fixed:"fixed",gid:"gid",hasChildren:"hasChildren",
icon:"icon",id:"id",objects:"rows",pid:"pid",rows:"rows",selected:"selected",statusIcon:"statusIcon",style:"style",subobjects:"cells",text:"text",tooltip:"tooltip",value:"value",visible:"visible"};this.dataService&&this.dataService.updateDataFields(this.options.rowFields,this.rowDataKey)};b.prototype.updateCellFields=function(a){this.options.cellFields=a?{allowEdit:a.allowEdit?a.allowEdit:"allowEdit",cid:a.cid?a.cid:"cid",content:a.content?a.content:"content",contextMenu:a.contextMenu?a.contextMenu:
"contextMenu",enabled:a.enabled?a.enabled:"enabled",isGroup:a.isGroup?a.isGroup:"isGroup",labelEdit:a.labelEdit?a.labelEdit:"labelEdit",rid:a.rid?a.rid:"rid",selected:a.selected?a.selected:"selected",style:a.style?a.style:"style",tag:a.tag?a.tag:"tag",templateObj:a.templateObj?a.templateObj:"templateObj",text:a.text?a.text:"text",tooltip:a.tooltip?a.tooltip:"tooltip",value:a.value?a.value:"value",valueID:a.valueID?a.valueID:"valueID",valueType:a.valueType?a.valueType:"valueType"}:{allowEdit:"allowEdit",
cid:"cid",content:"content",contextMenu:"contextMenu",enabled:"enabled",isGroup:"isGroup",labelEdit:"labelEdit",rid:"rid",selected:"selected",style:"style",tag:"tag",templateObj:"templateObj",text:"text",tooltip:"tooltip",value:"value",valueID:"valueID",valueType:"valueType"}};b.prototype.updateShowScroll=function(a){this.options.showScroll=a?{horizontal:this.commonService.isFieldAvailable(a.horizontal,!0),vertical:this.commonService.isFieldAvailable(a.vertical,!0)}:{horizontal:!0,vertical:!0}};b.prototype.processLoadData=
function(a,c,e,d){var b=this;b.clearRows(c);b.updateRowFields(e);var f=[];if(a)if(0!=d){var g=[];a.forEach(function(a,c){var e=a[b.options.rowFields.pid];g[e]?(g[e][b.options.rowFields.rows]||(g[e][b.options.rowFields.rows]=[]),g[a[b.options.rowFields.id]]=a,g[e][b.options.rowFields.rows].push(a)):(g[a[b.options.rowFields.id]]=a,f.push(a))});g.length=0}else f=a;if(c)for(c[b.options.rowFields.rows]=f,a=0;a<c[b.options.rowFields.rows].length;a++)c[b.options.rowFields.rows][a][b.options.rowFields.pid]=
c[b.options.rowFields.id];else if(b.rows)for(a=b.rows.length=0;a<f.length;a++)b.rows.push(f[a]);b.loadComplete.emit(null);this.updateLayout()};b.prototype.updateScrollColumnList=function(){};b.prototype.updateScrollRowList=function(){};b.prototype.addDropMark=function(a){this.appRef&&(this.removeDropMark(),a=this.cmpResolver.resolveComponentFactory(integralui_core_1.IntegralUIDragWindow))&&(this.dragCmpRef=this.appRef.createComponent(a),this.dragCmpRef._component?this.dragCmp=this.dragCmpRef._component:
this.dragCmpRef._hostElement&&(this.dragCmp=this.dragCmpRef._hostElement.component))};b.prototype.removeDropMark=function(){this.dragCmpRef&&this.dragCmpRef.destroy();this.dragCmp=null};b.prototype.callDragDropEvent=function(a,c,e){var d=this;c={action:c.action,cancel:!1,dragRow:c.source,dropPos:c.dropPos,event:a,isDropAllowed:c.allow,mousePos:this.commonService.getMousePos(a),resume:function(){d.drop(a,d.dragDropService.getData());d.dragDropService.clearData()},sourceCtrl:c.sourceCtrl,targetCtrl:c.targetCtrl,
targetRow:c.target};e?this.dragDrop.emit(c):this.dragOver.emit(c);return c.cancel};b.prototype.checkEmptySpace=function(a){var c=this.getContentSize(),e=this.commonService.getPageRect(this.elemRef.nativeElement.firstElementChild);c=e.top+c.height;e=e.bottom;a=this.commonService.getMousePos(a);var d=this.commonService.getShiftPos();a.x-=d.x;a.y-=d.y;return a.y>=c&&a.y<=e};b.prototype.ctrlDragDrop=function(a){this.isEnabled&&this.processDragDrop(a);a.stopPropagation()};b.prototype.ctrlDragLeave=function(a){this.isEnabled&&
(this.dropMark(a),this.stopScrollTimer())};b.prototype.ctrlDragOver=function(a){this.isEnabled&&this.processDragOver(a);a.stopPropagation()};b.prototype.dropMark=function(a,c){this.dragCmp||this.addDropMark({x:a.pageX,y:a.pageY});if(this.dragCmp){var e="none";this.options.allowDrop&&(e=c?"block":"none");this.dragCmp.display=e}};b.prototype.updateDragComponent=function(a){this.dragCmp&&this.dragCmp.updatePos(a)};b.prototype.isDragAllowed=function(a){return this.options.allowDrag?a&&(a[this.options.rowFields.allowDrag]||
void 0===a[this.options.rowFields.allowDrag])?!0:!1:!1};b.prototype.isDropAllowed=function(a,c,e){var d=this.options.allowDrop;if(d&&a&&c&&(d=c[this.options.rowFields.allowDrop]||void 0===c[this.options.rowFields.allowDrop]?!0:!1))if(Array.isArray(a))for(var b=0;b<a.length;b++){if(this.commonService.isEqual(a[b][this.options.rowFields.id],c[this.options.rowFields.id])||0===e&&this.isParentOf(c,a[b])||this.isChildOf(c,a[b])){d=!1;break}if(!d)break}else if(this.commonService.isEqual(a[this.options.rowFields.id],
c[this.options.rowFields.id])||0===e&&this.isParentOf(c,a)||this.isChildOf(c,a))d=!1;return d};b.prototype.processDragStart=function(a,c){this.dragDropService.clearData();if(!this.isDragAllowed(c))a.preventDefault();else if(c)if(this.isDragAllowed(c)){this.addDropMark({x:a.pageX,y:a.pageY});this.dropMark(a);a.dataTransfer?(a.dataTransfer.effectAllowed="move",a.dataTransfer.setData("text",c[this.options.rowFields.id]?c[this.options.rowFields.id].toString():"")):a.originalEvent&&a.originalEvent.dataTransfer&&
(a.originalEvent.dataTransfer.effectAllowed="move",a.originalEvent.dataTransfer.setData("text",c[this.options.rowFields.id]?c[this.options.rowFields.id].toString():""));var e={clone:this.cloneRow(c),source:c,sourceCtrl:this,sourceData:this.rows};switch(this.selectionMode){case integralui_core_1.IntegralUISelectionMode.MultiSimple:e.clone=this.createCloneList(this.currentSelectedRows);e.source=this.currentSelectedRows;break;case integralui_core_1.IntegralUISelectionMode.MultiExtended:e.clone=this.createCloneList(this.currentSelectedRows),
e.source=this.currentSelectedRows}this.dragDropService.setData(e)}else a.dataTransfer?a.dataTransfer.effectAllowed="none":a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.effectAllowed="none")};b.prototype.processDragOver=function(a,c,e,d){a.preventDefault();var b=!0;a.dataTransfer?b="none"===a.dataTransfer.effectAllowed?!1:!0:a.originalEvent&&a.originalEvent.dataTransfer&&(b="none"===a.originalEvent.dataTransfer.effectAllowed?!1:!0);if(b){var f=this.dragDropService.getData();
b=this.commonService.getShiftPos();if(c){var g=this.commonService.getMousePos(a);g.x-=b.x;g.y-=b.y;g=this.dragDropService.getDropPos(g,e,d,"group"==c.type?"full":null);b=this.isDropAllowed(f.source,c,g);e={action:a.shiftKey?"copy":"move",source:f.source,dropPos:g,allow:b,sourceCtrl:f.sourceCtrl,target:c,targetCtrl:this};e=this.callDragDropEvent(a,e);if(b&&1!=e){d=this.commonService.getMousePos(a);e=d.y+16;d=d.x+20;var l="iui-dragwin-icon";switch(g){case 0:l+=" iui-dragwin-move-in";break;case 1:l+=
" iui-dragwin-move-up";break;case 2:l+=" iui-dragwin-move-down"}a.shiftKey&&(l+="-copy");this.updateDragComponent({"class":l,top:e,left:d,text:c[this.options.rowFields.text]});this.dropMark(a,b);this.dragDropService.setData({action:a.shiftKey?"copy":"move",source:f.source,sourceCtrl:f.sourceCtrl,sourceData:f.sourceData,target:c,targetCtrl:this,dropPos:g})}else a.dataTransfer?a.dataTransfer.dropEffect="none":a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.dropEffect="none"),
this.dropMark(a)}else this.options.allowDrop?(b=this.checkEmptySpace(a),e={action:a.shiftKey?"copy":"move",source:f.source,dropPos:-1,allow:b,sourceCtrl:f.sourceCtrl,target:null,targetCtrl:this},e=this.callDragDropEvent(a,e),b&&1!=e?(g=this.commonService.getMousePos(a),e=g.y+16,d=g.x+20,l="iui-dragwin-icon iui-dragwin-move-end",a.shiftKey&&(l+="-copy"),this.updateDragComponent({"class":l,top:e,left:d,text:this.name?this.name:"Component"}),this.dropMark(a,b),this.dragDropService.setData({action:a.shiftKey?
"copy":"move",source:f.source,sourceCtrl:f.sourceCtrl,sourceData:f.sourceData,target:null,targetCtrl:this,dropPos:-1})):(a.dataTransfer?a.dataTransfer.dropEffect="none":a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.dropEffect="none"),this.dropMark(a))):(a.dataTransfer?a.dataTransfer.dropEffect="none":a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.dropEffect="none"),this.dropMark(a))}};b.prototype.processDragDrop=function(a,c){a.preventDefault();
this.dropMark(a);var e=!0;a.dataTransfer?e="none"===a.dataTransfer.effectAllowed?!1:!0:a.originalEvent&&a.originalEvent.dataTransfer&&(e="none"===a.originalEvent.dataTransfer.effectAllowed?!1:!0);if(e){var d=this.dragDropService.getData();(e=c?this.isDropAllowed(d.source,c,d.dropPos):this.checkEmptySpace(a))&&d.source&&(this.callDragDropEvent(a,{action:a.shiftKey?"copy":"move",source:d.source,dropPos:d.dropPos,allow:e,sourceCtrl:d.sourceCtrl,target:d.target,targetCtrl:this},!0)?e=!1:this.drop(a,d))}e&&
this.dragDropService.clearData()};b.prototype.drop=function(a,c){if(c&&c.sourceCtrl){var e=a.shiftKey&&c.clone?c.clone:c.source;if(Array.isArray(e)){for(var d=[],b=0;b<e.length;b++)d.push(e[b]);if(0<d.length){for(b=0;b<d.length;b++)this.processDataDrop(a,d[b],c);this.clearPrevSelection(d[d.length-1])}}else this.processDataDrop(a,e,c),this.clearPrevSelection(e);c.sourceCtrl!=c.targetCtrl&&c.sourceCtrl.updateLayout&&c.sourceCtrl.updateLayout();this.updateLayout()}};b.prototype.processDataDrop=function(a,
c,e){var d=a.shiftKey;!a.shiftKey&&e.sourceCtrl&&e.sourceCtrl.removeRow&&(d=e.sourceCtrl.removeRow(c));if(d)switch(e.dropPos){case 0:this.insertRowAt(c,-1,e.target);break;case 1:this.insertRowBefore(c,e.target);break;case 2:this.insertRowAfter(c,e.target);break;default:this.addRow(c)}};b.prototype.callAfterSelectEvent=function(a){this.afterSelect.emit({obj:a});this.selectionChanged.emit(null)};b.prototype.convertToCSV=function(a){for(var c="",e=0;e<a.length;e++){var d="",b=a[e];if(0<b.length){for(var f=
0;f<b.length;f++)d+=b[f].text+",";d=d.slice(0,-1);d+="\r\n"}c+=d}return c};b.prototype.exportToCSV=function(){for(var a=[],c=[],e=0;e<this.currentColumnList.length;e++){var d=this.currentColumnList[e].data;d={text:void 0!=d[this.options.columnFields.headerText]?d[this.options.columnFields.headerText].toString():""};c.push(d)}a.push(c);for(var b=this.getFullList(),f=0;f<b.length;f++){var g=b[f];c=[];for(e=0;e<this.currentColumnList.length;e++){var l=this.getCellByColumnId(g[this.options.rowFields.cells],
this.currentColumnList[e].data[this.options.columnFields.id]);d={};d.text=l?l.value?l.value instanceof Date?l.value.toLocaleDateString():JSON.stringify(l.value):l.text?0<=l.text.indexOf(",")?JSON.stringify(l.text):l.text:"":"";c.push(d)}a.push(c)}return this.convertToCSV(a)};b.prototype.exportToJSON=function(a,c,e,d){a=this.exportColumnsToJSON(a,e);c=this.exportRowsToJSON(c,e,d);return'[\n{ "columns": '+a+' },\n{ "rows": '+c+" }\n]"};b.prototype.exportColumnsToJSON=function(a,c){return JSON.stringify(this.columns,
a?a:[this.options.columnFields.allowDrag,this.options.columnFields.allowDrop,this.options.columnFields.allowFilter,this.options.columnFields.allowGrouping,this.options.columnFields.allowResize,this.options.columnFields.canSelect,this.options.columnFields.cellTemplateUrl,this.options.columnFields.columns,this.options.columnFields.contentAlignment,this.options.columnFields.contextMenu,this.options.columnFields.editorType,this.options.columnFields.editorSettings,this.options.columnFields.editorTemplate,
this.options.columnFields.filterParams,this.options.columnFields.fixed,this.options.columnFields.fixedWidth,this.options.columnFields.footerAlignment,this.options.columnFields.footerContent,this.options.columnFields.footerText,this.options.columnFields.footerTooltip,this.options.columnFields.groupText,this.options.columnFields.headerAlignment,this.options.columnFields.headerContent,this.options.columnFields.headerText,this.options.columnFields.headerTooltip,this.options.columnFields.icon,this.options.columnFields.id,
this.options.columnFields.minWidth,this.options.columnFields.maxWidth,this.options.columnFields.pid,this.options.columnFields.selected,this.options.columnFields.style,this.options.columnFields.visible,this.options.columnFields.width],c?c:null)};b.prototype.exportRowsToJSON=function(a,c,e){c=c?c:null;var d=0==e?this.rows:this.getFullList();a=a?a:[this.options.rowFields.allowCellFocus,this.options.rowFields.allowDrag,this.options.rowFields.allowDrop,this.options.rowFields.allowEdit,this.options.rowFields.allowFocus,
this.options.rowFields.autoCheck,this.options.rowFields.canSelect,this.options.rowFields.cells,this.options.rowFields.checked,this.options.rowFields.checkState,this.options.rowFields.content,this.options.rowFields.contextMenu,this.options.rowFields.gid,this.options.rowFields.enabled,this.options.rowFields.expanded,this.options.rowFields.fixed,this.options.rowFields.hasChildren,this.options.rowFields.icon,this.options.rowFields.id,this.options.rowFields.pid,this.options.rowFields.selected,this.options.rowFields.statusIcon,
this.options.rowFields.style,this.options.rowFields.text,this.options.rowFields.tooltip,this.options.rowFields.value,this.options.rowFields.visible,this.options.cellFields.allowEdit,this.options.cellFields.cid,this.options.cellFields.content,this.options.cellFields.contextMenu,this.options.cellFields.enabled,this.options.cellFields.isGroup,this.options.cellFields.rid,this.options.cellFields.selected,this.options.cellFields.style,this.options.cellFields.tag,this.options.cellFields.text,this.options.cellFields.tooltip,
this.options.cellFields.value,this.options.cellFields.valueID,this.options.cellFields.valueType];0==e&&a.push(this.options.rowFields.rows);return JSON.stringify(d,a,c)};b.prototype.filter=function(a,c){if(a)a[this.options.columnFields.filterParams]=c;else for(var e=0;e<this.currentColumnList.length;e++)this.currentColumnList[e].data[this.options.columnFields.filterParams]=null;this.updateLayout();this.change.emit({type:"filtering"})};b.prototype.cloneRow=function(a){return this.dataService.clone(a,
this.rowDataKey)};b.prototype.createCloneList=function(a){for(var c=[],e=0;e<a.length;e++)c.push(this.cloneRow(a[e]));return c};b.prototype.getCellByColumnId=function(a,c){var e=null;if(a)for(var d=0;d<a.length;d++)if(a[d][this.options.cellFields.cid]==c){e=a[d];break}return e};b.prototype.getCellWidth=function(a,c){var e=this.getColumnWidth(c);c&&this.getColumnIndexFromList(c)==this.expandColIndex&&(e-=a.indent);return 0<e?e:0};b.prototype.getColumnAllowResize=function(a){return(a=a[this.options.columnFields.allowResize])?
{left:this.commonService.isFieldAvailable(a.left,!0),right:this.commonService.isFieldAvailable(a.right,!0)}:{left:!0,right:!0}};b.prototype.getColumnById=function(a){var c=null,e=this.dataService.getList(null,this.columnDataKey);if(e)for(var d=0;d<e.length;d++)if(e[d][this.options.columnFields.id]==a){c=e[d];break}return c};b.prototype.getColumnCurrentIndex=function(a){return a?this.getColumnIndexFromList(a):-1};b.prototype.getColumnIndexFromList=function(a){for(var c=-1,e=0;e<this.currentColumnList.length;e++)if(this.currentColumnList[e].data==
a){c=e;break}return c};b.prototype.getColumnWidth=function(a,c){var e=this.options.columnFields.width;switch(c){case "min":return e=this.options.columnFields.minWidth,a&&void 0!=a[e]?a[e]:0;case "max":return e=this.options.columnFields.maxWidth,a&&void 0!=a[e]?a[e]:9999999}return a&&void 0!=a[e]?a[e]:100};b.prototype.setColumnWidth=function(a,c){if(a&&1!=a[this.options.columnFields.fixedWidth]){var e=this.getColumnWidth(a,"min"),d=this.getColumnWidth(a,"max");e=Math.min(d,Math.max(e,c));a[this.options.columnFields.width]=
1<e?e:0}};b.prototype.getPrevColumn=function(a,c){var e=null,d=this.getColumnIndexFromList(a)-1;if(0<=d)for(;0<=d;d--){var b=this.getColumnWidth(this.currentColumnList[d].data),f=this.getColumnWidth(this.currentColumnList[d].data,"min");b=c?!0:b>f;if(!this.isColumnWidthFixed(d)&&b){e=this.currentColumnList[d].data;break}}return e};b.prototype.getExpandingColumn=function(){return 0<=this.expandColIndex&&this.expandColIndex<this.currentColumnList.length?this.currentColumnList[this.expandColIndex].data:
null};b.prototype.getFilterTree=function(a){for(var c=null,e=0;e<this.currentColumnList.length;e++)if(this.currentColumnList[e].data==a){c=this.currentColumnList[e].filter;break}return c};b.prototype.getCurrentList=function(){for(var a=[],c=0;c<this.currentRowList.length;c++)a.push(this.currentRowList[c].data);return a};b.prototype.getList=function(a,c){switch(a){case "current":return this.getCurrentList();case "selected":return this.currentSelectedRows}return this.dataService.getList(c,this.rowDataKey)};
b.prototype.getFullList=function(){return[]};b.prototype.getTopRow=function(){return 0<this.scrollRowList.length?this.scrollRowList[0].data:null};b.prototype.getObjFromRow=function(a){for(var c=null,e=0;e<this.currentRowList.length;e++)if(this.currentRowList[e].data==a){c=this.currentRowList[e];break}return c};b.prototype.getRowCurrentIndex=function(a){return a?(a=this.getObjFromRow(a))&&this.currentRowList?this.currentRowList.indexOf(a):-1:-1};b.prototype.getRowIndent=function(a,c){var e=this.columnPadding.left;
this.isExpandBoxAllowed(c)&&(e+=a.indent);return e};b.prototype.getRowFromComponent=function(a){return null};b.prototype.isChildOf=function(a,c){return!1};b.prototype.isColumnVisible=function(a){return a&&0!=a[this.options.columnFields.visible]?!0:!1};b.prototype.isColumnWidthFixed=function(a){return 0<=a&&a<this.currentColumnList.length?1==this.currentColumnList[a].data[this.options.columnFields.fixedWidth]:!1};b.prototype.isComponentIndexInRange=function(a){return this.rowList?0<=a&&a<this.rowList.length:
!1};b.prototype.isExpandBoxAllowed=function(a){return a?this.getColumnIndexFromList(a)==this.expandColIndex:!1};b.prototype.isIndexInRange=function(a){return this.currentRowList?0<=a&&a<this.currentRowList.length:!1};b.prototype.isRowAllowed=function(a,c){if(0==a[this.options.rowFields.visible])return!1;if(0==this.options.allowFilter)return!0;var e=!0;if(a)for(var d,b,f=0;f<a[this.options.rowFields.cells].length;f++){e=!0;b=a[this.options.rowFields.cells][f];d=b[this.options.cellFields.cid];d=this.getColumnById(d);
!d&&f<this.currentColumnList.length&&(d=this.currentColumnList[f].data);if(d&&d[this.options.columnFields.filterParams]){var g=d[this.options.columnFields.filterParams],l=b[this.options.cellFields.value]?b[this.options.cellFields.value]:b[this.options.cellFields.text];g&&(g.callback?e=g.callback(l,b,a):(e=this.filterService.match(l,g.conditions,g.formula,this.getFilterTree(d),g.caseSensitive),!e&&g.allowParent&&(e=this.filterIsThereChildren(a,c))))}if(!e)break}return e};b.prototype.filterIsThereChildren=
function(a,c){var e=!1,d=a[this.options.rowFields.rows];if(d)for(var b=0;b<d.length&&!(e=this.isRowAllowed(d[b],c));b++);return e};b.prototype.isRowEnabled=function(a){return!0};b.prototype.isRowFixed=function(a){return!1};b.prototype.isRowHovered=function(a){return a&&a==this.hoverRow?!0:!1};b.prototype.isRowSelected=function(a){return a&&1==a[this.options.rowFields.selected]?!0:!1};b.prototype.isParentOf=function(a,c){return!1};b.prototype.processStateChanged=function(){this.updateLayout()};b.prototype.updateExpandStatus=
function(){};b.prototype.resetReorderColumnSettings=function(){this.reorderColumn=null;this.columnReorderActive=!1};b.prototype.cellGotFocus=function(a){this.isEnabled&&this.refresh()};b.prototype.cellLostFocus=function(a){this.isEnabled&&this.refresh()};b.prototype.onContentScroll=function(a){a.srcElement.scrollTop=0;a.srcElement.scrollLeft=0;a.target.scrollTop=0;a.target.scrollLeft=0};b.prototype.onGridScroll=function(a){a.srcElement.scrollTop=0;a.srcElement.scrollLeft=0;a.target.scrollTop=0;a.target.scrollLeft=
0};b.prototype.cellMouseDown=function(a,c){this.isEnabled&&1==a.buttons&&(this.currentFocusCell=c.data)};b.prototype.cellKeyDown=function(a,c){if(this.isEnabled){var e={cancel:!1,cell:c.data,event:a};this.keyDown.emit(e);switch(a.keyCode){case 13:this.beforeEdit.emit(e);break;case 33:!e.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processPageUpKey(c));break;case 34:!e.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processPageDownKey(c));
break;case 35:!e.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processEndKey(c));break;case 36:!e.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processHomeKey(c));break;case 37:!e.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processLeftArrowKey(c));break;case 38:!e.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processUpArrowKey(c));break;case 39:!e.cancel&&
this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processRightArrowKey(c));break;case 40:!e.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processDownArrowKey(c))}}};b.prototype.cellKeyPress=function(a,c){var e={cancel:!1,cell:c.data,event:a};this.isEnabled&&this.keyPress.emit(e)};b.prototype.cellKeyUp=function(a,c){var e={cancel:!1,cell:c.data,event:a};this.isEnabled&&this.keyUp.emit(e)};b.prototype.processDownArrowKey=function(a,c){var e=
this.getDownCell(a);if(e){this.currentFocusCell=e.data;var d=this.getRowFromCell(e),b=this,f=setTimeout(function(){b.processRowSelection(c,d.data);clearTimeout(f)},1);this.isLastRow(e)&&this.scrollPos({x:this.currentScrollPos.x,y:this.currentScrollPos.y+2*this.avgRowHeight})}return e};b.prototype.processEndKey=function(a,c){var e=null;if(0<this.scrollRowList.length){this.scrollPos({x:this.currentScrollPos.x,y:this.maxScrollPos.y});var d=this;setTimeout(function(){var b=d.scrollRowList[d.scrollRowList.length-
1];if(0<=a.colIndex&&a.colIndex<b.cells.length){e=b.cells[a.colIndex];d.currentFocusCell=e.data;var f=setTimeout(function(){d.processRowSelection(c,b.data);clearTimeout(f)},1)}},1)}return e};b.prototype.processHomeKey=function(a,c){var e=null;if(0<this.scrollRowList.length){this.scrollPos({x:this.currentScrollPos.x,y:0});var d=this;setTimeout(function(){var b=d.scrollRowList[0];if(0<=a.colIndex&&a.colIndex<b.cells.length){e=b.cells[a.colIndex];d.currentFocusCell=e.data;var f=setTimeout(function(){d.processRowSelection(c,
b.data);clearTimeout(f)},1)}},1)}return e};b.prototype.processLeftArrowKey=function(a){if(a=this.getPrevCell(a)){this.currentFocusCell=a.data;this.isFirstCell(a)&&this.scrollPos({x:this.currentScrollPos.x-2*a.width,y:this.currentScrollPos.y});var c=this;setTimeout(function(){c.refresh()},1)}return a};b.prototype.processPageDownKey=function(a,c){var e=null;if(0<this.scrollRowList.length){this.scrollPos({x:this.currentScrollPos.x,y:this.currentScrollPos.y+this.avgRowHeight*(this.scrollRowList.length-
1)});var d=this;setTimeout(function(){var b=0<=a.rowIndex&&a.rowIndex<d.scrollRowList.length?a.rowIndex:d.scrollRowList.length-1;d.currentScrollPos.y==d.maxScrollPos.y&&(b=d.scrollRowList.length-1);var f=d.scrollRowList[b];if(0<=a.colIndex&&a.colIndex<f.cells.length){e=f.cells[a.colIndex];d.currentFocusCell=e.data;var g=setTimeout(function(){d.processRowSelection(c,f.data);clearTimeout(g)},1)}},1)}return e};b.prototype.processPageUpKey=function(a,c){var e=null;if(0<this.scrollRowList.length){this.scrollPos({x:this.currentScrollPos.x,
y:this.currentScrollPos.y-this.avgRowHeight*(this.scrollRowList.length-1)});var d=this;setTimeout(function(){var b=0<=a.rowIndex&&a.rowIndex<d.scrollRowList.length?a.rowIndex:0;0==d.currentScrollPos.y&&(b=0);var f=d.scrollRowList[b];if(0<=a.colIndex&&a.colIndex<f.cells.length){e=f.cells[a.colIndex];d.currentFocusCell=e.data;var g=setTimeout(function(){d.processRowSelection(c,f.data);clearTimeout(g)},1)}},1)}return e};b.prototype.processRightArrowKey=function(a){if(a=this.getNextCell(a)){this.currentFocusCell=
a.data;this.isLastCell(a)?this.scrollPos({x:this.currentScrollPos.x+2*a.width,y:this.currentScrollPos.y}):a.colIndex>=this.currentColumnList.length-2&&this.scrollPos({x:this.maxScrollPos.x,y:this.currentScrollPos.y});var c=this;setTimeout(function(){c.refresh()},1)}return a};b.prototype.processUpArrowKey=function(a,c){var e=this.getUpCell(a);if(e){this.currentFocusCell=e.data;var d=this.getRowFromCell(e),b=this,f=setTimeout(function(){b.processRowSelection(c,d.data);clearTimeout(f)},1);this.isFirstRow(e)&&
this.scrollPos({x:this.currentScrollPos.x,y:this.currentScrollPos.y-this.avgRowHeight})}return e};b.prototype.getDownCell=function(a){if(0<=a.rowIndex&&a.rowIndex<this.scrollRowList.length){var c=a.rowIndex<this.scrollRowList.length-1?a.rowIndex+1:-1;return(c=0<=c?this.scrollRowList[c]:null)&&0<=a.colIndex&&a.colIndex<c.cells.length?c.cells[a.colIndex]:null}return null};b.prototype.getNextCell=function(a){if(0<=a.rowIndex&&a.rowIndex<this.scrollRowList.length){var c=this.scrollRowList[a.rowIndex];
a=c.cells.indexOf(a);a=0<=a&&a<c.cells.length-1?a+1:-1;return 0<=a?c.cells[a]:null}return null};b.prototype.getPrevCell=function(a){if(0<=a.rowIndex&&a.rowIndex<this.scrollRowList.length){var c=this.scrollRowList[a.rowIndex];a=c.cells.indexOf(a);a=0<a&&a<c.cells.length?a-1:-1;return 0<=a?c.cells[a]:null}return null};b.prototype.getUpCell=function(a){if(0<=a.rowIndex&&a.rowIndex<this.scrollRowList.length){var c=0<a.rowIndex?a.rowIndex-1:-1;return(c=0<=c?this.scrollRowList[c]:null)&&0<=a.colIndex&&
a.colIndex<c.cells.length?c.cells[a.colIndex]:null}return null};b.prototype.isFirstCell=function(a){return 0==a.colIndex?!0:!1};b.prototype.isFirstRow=function(a){return 0==a.rowIndex?!0:!1};b.prototype.isLastCell=function(a){return a.colIndex==this.viewIndexRange.middle-this.viewIndexRange.left?!0:!1};b.prototype.isLastRow=function(a){return a.rowIndex==this.scrollRowList.length-2?!0:!1};b.prototype.getRowFromCell=function(a){return 0<=a.rowIndex&&a.rowIndex<this.scrollRowList.length?this.scrollRowList[a.rowIndex]:
null};b.prototype.moveFocusFromCell=function(a,c){if(!this.options.allowFocus)return null;var e=null,b=this.getObjFromCell(a);if(b)switch(c){case "down":e=this.processDownArrowKey(b);break;case "end":e=this.processEndKey(b);break;case "home":e=this.processHomeKey(b);break;case "left":e=this.processLeftArrowKey(b);break;case "pagedown":e=this.processPageDownKey(b);break;case "pageup":e=this.processPageUpKey(b);break;case "right":e=this.processRightArrowKey(b);break;case "up":e=this.processUpArrowKey(b)}return e?
e.data:null};b.prototype.getObjFromCell=function(a){for(var c=null,b=0;b<this.scrollRowList.length;b++)for(var d=this.scrollRowList[b],h=0;h<d.cells.length;h++){var f=d.cells[h];if(f.data==a){c=f;break}}return c};b.prototype.onWindowKeyDown=function(a){this.isEnabled&&this.isKeyboardActive&&a.preventDefault()};b.prototype.onWindowKeyUp=function(a){this.isKeyboardActive=!1};b.prototype.getContentSize=function(){return{width:0,height:0}};b.prototype.refresh=function(a){this.clearComponentSelection();
for(a=0;a<this.currentSelectedRows.length;a++){var c=this.getRowCurrentIndex(this.currentSelectedRows[a]);this.isComponentIndexInRange(c)&&(this.rowList[c].state|=integralui_core_1.IntegralUIObjectState.selected)}};b.prototype.suspendLayout=function(){this.allowUpdate=!1};b.prototype.resumeLayout=function(){this.allowUpdate=!0;this.updateLayout()};b.prototype.updateLayout=function(){};b.prototype.updateColumnWidth=function(){if(this.isAutoSizeColumnsActive){for(var a=0,c,b,d=0,h=[],f=0;f<this.currentColumnList.length;f++)c=
this.getColumnWidth(this.currentColumnList[f].data),b=this.getColumnWidth(this.currentColumnList[f].data,"min"),c>=b&&(a+=c+this.columnPadding.left+this.columnPadding.right+6,1!=this.currentColumnList[f].data[this.options.columnFields.fixedWidth]&&(d++,h.push(this.currentColumnList[f])));0<d&&(c=this.isVerScrollVisible()?20:0,this.updateColumnWidthByFactor(h,(this.clientRect.width-c-a)/d))}};b.prototype.updateColumnWidthByFactor=function(a,c){var b=0;var d=0;for(var h=[],f=0;f<a.length;f++){var g=
this.getColumnWidth(a[f].data);var l=this.getColumnWidth(a[f].data,"min");1==a[f].data[this.options.columnFields.fixedWidth]&&(l=g);g>=l&&(g+c<=l?(b+=g+c-l,this.setColumnWidth(a[f].data,l),this.updateCellWidth(a[f].data)):(h.push(a[f]),d++))}if(0<d)if(g=b/d,0!=g)this.updateColumnWidthByFactor(h,c+g);else for(f=0;f<h.length;f++)g=this.getColumnWidth(h[f].data)+c,this.setColumnWidth(h[f].data,g),this.updateCellWidth(h[f].data)};b.prototype.checkWidthChanges=function(){if(this.isAutoSizeColumnsActive){for(var a=
0,c,b=0;b<this.currentColumnList.length;b++)c=this.getColumnWidth(this.currentColumnList[b].data),this.getColumnWidth(this.currentColumnList[b].data,"min"),a+=c+this.columnPadding.left+this.columnPadding.right+6;b=this.isVerScrollVisible()?20:0;a=this.clientRect.width-b-a-2;if(0<a)for(b=this.currentColumnList.length-1;0<=b;b--)if(!this.isColumnWidthFixed(b)){c=this.getColumnWidth(this.currentColumnList[b].data)+a;this.setColumnWidth(this.currentColumnList[b].data,c);this.updateCellWidth(this.currentColumnList[b].data);
break}}};b.prototype.updateCellWidth=function(a){for(var c=0;c<this.scrollRowList.length;c++)for(var b=this.scrollRowList[c],d=this.getColumnCurrentIndex(a),h=0;h<b.cells.length;h++)if(b.cells[h].colIndex==d-this.viewIndexRange.left){d=this.getCellWidth(b,a);if(this.getColumnIndexFromList(a)==this.expandColIndex){var f=this.getColumnWidth(a);f=0<f?f:this.columnPadding.left;b.cells[h].indent=0==d?f:this.getRowIndent(b,a)}b.cells[h].width=d;break}};b.prototype.updateRange=function(){};b.prototype.onCtrlMouseEnter=
function(a){this.isEnabled&&1==a.buttons&&this.cloneElem&&(this.cloneElem.style.display="block");this.elemRenderer.setElementStyle(this.elemRef.nativeElement,"cursor","default")};b.prototype.onCtrlMouseLeave=function(a){this.isEnabled&&1==a.buttons&&this.cloneElem&&(this.cloneElem.style.display="none");this.stopScrollTimer()};b.prototype.updatePaging=function(a){this.options.paging=a?{enabled:this.commonService.isFieldAvailable(a.enabled,!1),showControlPanel:this.commonService.isFieldAvailable(a.showControlPanel,
!0),pageSize:this.commonService.isFieldAvailable(a.pageSize,100)}:{enabled:!1,showControlPanel:!0,pageSize:100}};b.prototype.scrollPos=function(a){a&&(this.currentScrollPos={x:Math.max(0,Math.min(a.x,this.maxScrollPos.x)),y:Math.max(0,Math.min(a.y,this.maxScrollPos.y))});return{x:Math.floor(this.currentScrollPos.x),y:Math.floor(this.currentScrollPos.y)}};b.prototype.changeHorizontalScrollPos=function(a){this.currentScrollPos.x=Math.max(0,Math.min(a,this.maxScrollPos.x));this.currentScrollPos.x!=this.prevScrollPos.x&&
(this.updateRange(),this.scrollPosChanged.emit({value:this.scrollPos()}),this.prevScrollPos.x=this.currentScrollPos.x)};b.prototype.changeVerticalScrollPos=function(a){this.currentScrollPos.y=Math.max(0,Math.min(a,this.maxScrollPos.y));this.currentScrollPos.y!=this.prevScrollPos.y&&(this.updateView(),this.scrollPosChanged.emit({value:this.scrollPos()}),this.prevScrollPos.y=this.currentScrollPos.y)};b.prototype.gridMouseWheel=function(a){a.preventDefault();if(this.isEnabled){this.hoverRow=null;var c=
Math.max(-1,Math.min(1,a.wheelDelta||-a.detail));this.isVerScrollVisible()&&this.changeVerticalScrollPos(this.currentScrollPos.y+Math.floor(this.clientRect.height/4)*c*-1)}a.stopPropagation()};b.prototype.isVerScrollVisible=function(){return this.isEnabled&&this.options.showScroll.vertical&&0<this.scrollSize.height?!0:!1};b.prototype.isHorScrollVisible=function(){return this.isEnabled&&this.options.showScroll.horizontal&&0<this.scrollSize.width?!0:!1};b.prototype.onVerticalScrollStart=function(a){this.hoverRow=
null;this.isScrollActive=!0};b.prototype.onVerticalScrollEnd=function(a){this.isScrollActive=!1};b.prototype.onVerticalScrollChanged=function(a){this.changeVerticalScrollPos(a.value)};b.prototype.onHorizontalScrollStart=function(a){this.hoverRow=null;this.isScrollActive=!0};b.prototype.onHorizontalScrollEnd=function(a){this.isScrollActive=!1};b.prototype.onHorizontalScrollChanged=function(a){this.currentScrollPos.x=a.value;this.scrollPosChanged.emit({value:this.scrollPos()});var c=this,b=setTimeout(function(){c.updateRange();
clearTimeout(b)},1)};b.prototype.updateView=function(){this.currentIndex=0<this.avgRowHeight?Math.floor(this.currentScrollPos.y/this.avgRowHeight):0;this.currentIndex!=this.prevIndex&&(this.updateScrollRowList(),this.prevIndex=this.currentIndex)};b.prototype.processScroll=function(a,c){if(this.isEnabled)if(this.isVerScrollVisible()){var b=this.commonService.getShiftPos(),d=this.commonService.getMousePos(a);d.x-=b.x;d.y-=b.y;var h=this.commonService.getPageRect(this.elemRef.nativeElement);b=h.top+
this.headerHeight+(c?c:0)+25;h=h.bottom-this.footerHeight-25;this.isHorScrollVisible()&&(h-=16);d.y<b?this.startScrollTimer(!1):d.y>h?this.startScrollTimer(!0):this.stopScrollTimer()}else this.stopScrollTimer()};b.prototype.startScrollTimer=function(a,c){var b=this;b.isScrollTimerActive||(b.accelerator=.5,b.scrollCount=0,b.isScrollTimerActive=!0,b.scrollTimerID=setInterval(function(){b.scrollTimerElapsed(a)},c?c:100))};b.prototype.stopScrollTimer=function(){this.scrollTimerID&&(clearInterval(this.scrollTimerID),
this.scrollTimerID=null);this.accelerator=.5;this.scrollCount=0;this.isScrollTimerActive=!1};b.prototype.scrollTimerElapsed=function(a){var c=this.currentScrollPos;0===this.scrollCount&&(this.scrollCount=5);this.scrollCount+=5;this.accelerator+=.5;var b=this.scrollCount+=Math.floor(this.accelerator);this.currentScrollPos.y=a?this.currentScrollPos.y+b>this.maxScrollPos.y?this.maxScrollPos.y:this.currentScrollPos.y+b:0>this.currentScrollPos.y-b?0:this.currentScrollPos.y-b;(0>=c.y||this.currentScrollPos.y<
c.y)&&this.stopScrollTimer()};b.prototype.scrollTo=function(a){a&&(a=this.getRowCurrentIndex(a),0<=a&&this.scrollPos({x:this.currentScrollPos.x,y:this.avgRowHeight*(a+1-this.visibleRange/2)}),this.updateLayout())};b.prototype.findRowById=function(a){return this.dataService.findObjectById(a,this.rowDataKey)};b.prototype.findRowByText=function(a){return this.dataService.findObjectByText(a,this.rowDataKey)};b.prototype.clearSelection=function(){this.clearPrevSelection();this.refresh()};b.prototype.processColumnSelection=
function(a,c,b){if(c)0!=c[this.options.columnFields.canSelect]&&(a=!0,this.currentSelectedColumn&&(a=!this.commonService.isEqual(this.currentSelectedColumn[this.options.columnFields.id],c[this.options.columnFields.id])),b={cancel:!1,obj:c},this.beforeSelect.emit(b),a&&1!=b.cancel&&(this.currentSelectedColumn&&(this.currentSelectedColumn[this.options.columnFields.selected]=!1,this.refresh(this.currentSelectedColumn)),this.currentSelectedColumn=c,c[this.options.columnFields.selected]=!0,this.refresh(c),
this.callAfterSelectEvent(c)));else return this.currentSelectedColumn};b.prototype.clearComponentSelection=function(){this.rowList.forEach(function(a){return a.state&=~integralui_core_1.IntegralUIObjectState.selected})};b.prototype.clearPrevSelection=function(a){for(var c=0;c<this.currentSelectedRows.length;c++)a&&!this.commonService.isEqual(this.currentSelectedRows[c][this.options.rowFields.id],a[this.options.rowFields.id])?this.currentSelectedRows[c][this.options.rowFields.selected]=!1:a||(this.currentSelectedRows[c][this.options.rowFields.selected]=
!1);this.currentSelectedRows.length=0;a&&this.isRowEnabled(a)&&this.currentSelectedRows.push(a)};b.prototype.isRowInSelectionList=function(a){var c=!1,b=this.currentSelectedRows;if(a&&b)for(var d=0;d<b.length;d++)if(this.commonService.isEqual(b[d][this.options.rowFields.id],a[this.options.rowFields.id])){c=!0;break}return c};b.prototype.processRowSelection=function(a,c,b){if(c&&this.selectionMode!=integralui_core_1.IntegralUISelectionMode.None&&0!=c[this.options.rowFields.canSelect]){var d=0<this.currentSelectedRows.length;
if(this.isRowEnabled(c)){var e=this.currentSelectedRow,f=!0;e&&(f=a&&(a.ctrlKey||a.metaKey)||!this.commonService.isEqual(e[this.options.rowFields.id],c[this.options.rowFields.id])||0==e[this.options.rowFields.selected]);var g={cancel:!1,obj:c};this.beforeSelect.emit(g);if(1!=g.cancel)if(g=a&&(a.shiftKey||a.ctrlKey||a.metaKey)?!0:!1,f){this.selectionMode==integralui_core_1.IntegralUISelectionMode.MultiExtended&&(f=!this.isRowInSelectionList(c)||!g||a&&a.shiftKey);f&&(this.selectionMode==integralui_core_1.IntegralUISelectionMode.One?
this.clearPrevSelection():a&&a.shiftKey?this.clearPrevSelection():g||this.selectionMode==integralui_core_1.IntegralUISelectionMode.MultiSimple||1!=this.currentSelectedRows.length&&this.isRowInSelectionList(c)||this.clearPrevSelection());this.currentSelectedRow=c;if(a&&a.shiftKey&&this.selectionMode!=integralui_core_1.IntegralUISelectionMode.One){if(this.shiftFirstSelectedRow||(this.shiftFirstSelectedRow=e),a=this.getRowCurrentIndex(this.shiftFirstSelectedRow),b=this.getRowCurrentIndex(c),a>b&&(d=
a,a=b,b=d),this.isIndexInRange(a)&&this.isIndexInRange(b))for(;a<=b;a++)0!=this.currentRowList[a].data[this.options.rowFields.canSelect]&&(this.currentRowList[a].data[this.options.rowFields.selected]=!0,this.currentSelectedRows.push(this.currentRowList[a].data))}else g||this.selectionMode==integralui_core_1.IntegralUISelectionMode.MultiSimple?(a=null==c[this.options.rowFields.selected]||"undefined"==c[this.options.rowFields.selected]?!1:c[this.options.rowFields.selected],c[this.options.rowFields.selected]=
!a,c[this.options.rowFields.selected]?this.isRowInSelectionList(c)||this.currentSelectedRows.push(c):this.currentSelectedRows=this.currentSelectedRows.filter(function(a){return a!=c})):(c[this.options.rowFields.selected]=!0,this.isRowInSelectionList(c)||this.currentSelectedRows.push(c)),this.shiftFirstSelectedRow=null;this.callAfterSelectEvent(c);this.refresh()}else g||this.selectionMode==integralui_core_1.IntegralUISelectionMode.MultiSimple?(a=null===c[this.options.rowFields.selected]||"undefined"==
c[this.options.rowFields.selected]?!1:c[this.options.rowFields.selected],b&&"undefined"!=b&&(a=b),c[this.options.rowFields.selected]=!a,c[this.options.rowFields.selected]?this.isRowInSelectionList(c)||this.currentSelectedRows.push(c):this.currentSelectedRows=this.currentSelectedRows.filter(function(a){return a!=c}),this.shiftFirstSelectedRow=null,this.callAfterSelectEvent(c),this.refresh()):g||this.selectionMode&integralui_core_1.IntegralUISelectionMode.MultiSimple||1!=this.currentSelectedRows.length&&
this.isRowInSelectionList(c)||(this.shiftFirstSelectedRow=null,this.clearPrevSelection(c),this.refresh(),d&&this.selectionChanged.emit(null))}else this.clearPrevSelection(),this.refresh(),d&&this.selectionChanged.emit(null)}};b.prototype.selectRows=function(a){if(a&&Array.isArray(a)){for(var c=this.currentSelectedRows.length=0;c<a.length;c++)a[c][this.options.rowFields.selected]=!0,this.currentSelectedRows.push(a[c]);0<a.length?(this.currentSelectedRow=a[a.length-1],this.callAfterSelectEvent(this.currentSelectedRow)):
this.currentSelectedRow=null;this.refresh()}};b.prototype.updateRowSelection=function(a,c){var b=a&&(a.shiftKey||a.ctrlKey||a.metaKey)?!0:!1;this.selectionMode==integralui_core_1.IntegralUISelectionMode.MultiExtended&&0!=c[this.options.rowFields.canSelect]&&0<this.currentSelectedRows.length&&!a.shiftKey&&!b&&1==a.which&&(b=this.currentSelectedRows.length,this.clearPrevSelection(),c[this.options.rowFields.selected]=!0,this.currentSelectedRows.push(c),1<b&&this.callAfterSelectEvent(c),this.refresh())};
b.prototype.sort=function(a,c,b){this.sortColumn=a;this.sortComparer=b;this.options.sorting=c;this.updateLayout();this.change.emit({type:"sorting"})};b.prototype.getCellIndexInCollection=function(a,b,e){var c=-1;if(a)for(var h=0;h<a.length;h++)if(void 0==a[h][this.options.cellFields.cid]){c=b;break}else if(a[h][this.options.cellFields.cid]==e){c=h;break}return c};b.prototype.isSortingAllowed=function(){return this.options.sorting==integralui_core_1.IntegralUISortOrder.Ascending||this.options.sorting==
integralui_core_1.IntegralUISortOrder.Descending};b.prototype.isSortingColumn=function(a){return a&&a==this.sortColumn?!0:!1};b.prototype.applySorting=function(a){var b=this;if(a&&(!b.sortColumn||0!=b.sortColumn[b.options.columnFields.visible])){var e=b.getColumnCurrentIndex(b.sortColumn),d=0<=e?e:b.options.expandColIndex;if(d<b.currentColumnList.length){var h=b.currentColumnList[d].data[b.options.columnFields.id];b.sortColumn&&b.sortColumn[b.options.columnFields.comparer]?a.sort(b.sortColumn[b.options.columnFields.comparer]):
b.sortComparer?a.sort(b.sortComparer):b.isSortingAllowed()&&a.sort(function(a,c){var e=null,f=null;if(a[b.options.rowFields.cells]){var g=b.getCellIndexInCollection(a[b.options.rowFields.cells],d,h);0<=g&&((e=a[b.options.rowFields.cells][g][b.options.cellFields.value])||(e=a[b.options.rowFields.cells][g][b.options.cellFields.text]),b.commonService.isObject(e)&&(e=e.value?e.value:e.text))}c[b.options.rowFields.cells]&&(g=b.getCellIndexInCollection(c[b.options.rowFields.cells],d,h),0<=g&&((f=c[b.options.rowFields.cells][g][b.options.cellFields.value])||
(f=c[b.options.rowFields.cells][g][b.options.cellFields.text]),b.commonService.isObject(f)&&(f=f.value?f.value:f.text)));e=void 0!=e?e:null;f=void 0!=f?f:null;switch(b.options.sorting){case integralui_core_1.IntegralUISortOrder.Ascending:if(e<f)return-1;if(e>f)return 1;break;case integralui_core_1.IntegralUISortOrder.Descending:if(e>f)return-1;if(e<f)return 1;break;default:return 0}})}}};return b}(integralui_core_1.IntegralUIBaseComponent);
__decorate([core_1.Input(),__metadata("design:type",Object)],IntegralUIBaseGrid.prototype,"appRef",void 0);__decorate([core_1.Input(),__metadata("design:type",Boolean)],IntegralUIBaseGrid.prototype,"autoUpdate",void 0);__decorate([core_1.Input(),__metadata("design:type",Number)],IntegralUIBaseGrid.prototype,"rowHeight",void 0);__decorate([core_1.Input(),__metadata("design:type",Boolean),__metadata("design:paramtypes",[Boolean])],IntegralUIBaseGrid.prototype,"allowDrag",null);
__decorate([core_1.Input(),__metadata("design:type",Boolean),__metadata("design:paramtypes",[Boolean])],IntegralUIBaseGrid.prototype,"allowDrop",null);__decorate([core_1.Input(),__metadata("design:type",Boolean),__metadata("design:paramtypes",[Boolean])],IntegralUIBaseGrid.prototype,"allowFilter",null);__decorate([core_1.Input(),__metadata("design:type",Boolean),__metadata("design:paramtypes",[Boolean])],IntegralUIBaseGrid.prototype,"allowFocus",null);
__decorate([core_1.Input(),__metadata("design:type",Boolean),__metadata("design:paramtypes",[Boolean])],IntegralUIBaseGrid.prototype,"autoSizeColumns",null);__decorate([core_1.Input(),__metadata("design:type",Array),__metadata("design:paramtypes",[Array])],IntegralUIBaseGrid.prototype,"columns",null);__decorate([core_1.Input(),__metadata("design:type",Object),__metadata("design:paramtypes",[Object])],IntegralUIBaseGrid.prototype,"dataFields",null);
__decorate([core_1.Input(),__metadata("design:type",Object),__metadata("design:paramtypes",[Object])],IntegralUIBaseGrid.prototype,"focusedCell",null);__decorate([core_1.Input(),__metadata("design:type",Number),__metadata("design:paramtypes",[Number])],IntegralUIBaseGrid.prototype,"gridLines",null);__decorate([core_1.Input(),__metadata("design:type",Object),__metadata("design:paramtypes",[Object])],IntegralUIBaseGrid.prototype,"paging",null);
__decorate([core_1.Input(),__metadata("design:type",Array),__metadata("design:paramtypes",[Array])],IntegralUIBaseGrid.prototype,"rows",null);__decorate([core_1.Input(),__metadata("design:type",Object),__metadata("design:paramtypes",[Object])],IntegralUIBaseGrid.prototype,"selectedColumn",null);__decorate([core_1.Input(),__metadata("design:type",Object),__metadata("design:paramtypes",[Object])],IntegralUIBaseGrid.prototype,"selectedRow",null);
__decorate([core_1.Input(),__metadata("design:type",Number),__metadata("design:paramtypes",[Number])],IntegralUIBaseGrid.prototype,"selectionMode",null);__decorate([core_1.Input(),__metadata("design:type",Object),__metadata("design:paramtypes",[Object])],IntegralUIBaseGrid.prototype,"showScroll",null);__decorate([core_1.Input(),__metadata("design:type",Number),__metadata("design:paramtypes",[Number])],IntegralUIBaseGrid.prototype,"sorting",null);
__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"afterSelect",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"beforeEdit",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"beforeSelect",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"beforeUpdate",void 0);
__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"change",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"columnAdding",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"columnAdded",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"columnClick",void 0);
__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"columnRemoving",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"columnRemoved",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"columnsCleared",void 0);
__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"columnSizeChanged",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"dragDrop",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"dragOver",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"keyDown",void 0);
__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"keyPress",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"keyUp",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"rowAdding",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"rowAdded",void 0);
__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"rowClick",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"rowDblClick",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"rowRemoving",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"rowRemoved",void 0);
__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"rowsCleared",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"loadComplete",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"scrollPosChanged",void 0);
__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"selectionChanged",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"updateComplete",void 0);__decorate([core_1.HostListener("document:keydown",["$event"]),__metadata("design:type",Function),__metadata("design:paramtypes",[Object]),__metadata("design:returntype",void 0)],IntegralUIBaseGrid.prototype,"onWindowKeyDown",null);
__decorate([core_1.HostListener("document:keyup",["$event"]),__metadata("design:type",Function),__metadata("design:paramtypes",[Object]),__metadata("design:returntype",void 0)],IntegralUIBaseGrid.prototype,"onWindowKeyUp",null);
IntegralUIBaseGrid=__decorate([core_1.Component({selector:"iui-basegrid",template:"",providers:[integralui_data_service_1.IntegralUIDataService]}),__metadata("design:paramtypes",[integralui_data_service_1.IntegralUIDataService,integralui_dragdrop_service_1.IntegralUIDragDropService,core_1.ElementRef,core_1.Renderer,integralui_common_service_1.IntegralUICommonService,integralui_filter_service_1.IntegralUIFilterService,core_1.ComponentFactoryResolver])],IntegralUIBaseGrid);
exports.IntegralUIBaseGrid=IntegralUIBaseGrid;